// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBybwIAqJH1VQ1CwK20ghZMHylODN3CIPE',
    appId: '1:279438736618:web:c896c7b643f12cf553eb93',
    messagingSenderId: '279438736618',
    projectId: 'cmenu-8af16',
    authDomain: 'cmenu-8af16.firebaseapp.com',
    storageBucket: 'cmenu-8af16.appspot.com',
    measurementId: 'G-4QBG0LHRHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVSnhyvNz9zwymXgTBTivBDEKfkijcM8',
    appId: '1:279438736618:android:0db7a473e321541753eb93',
    messagingSenderId: '279438736618',
    projectId: 'cmenu-8af16',
    storageBucket: 'cmenu-8af16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtwwXhgPk_WpaS8Pu1joPovte0OrBCP6g',
    appId: '1:279438736618:ios:c4a787c789646cde53eb93',
    messagingSenderId: '279438736618',
    projectId: 'cmenu-8af16',
    storageBucket: 'cmenu-8af16.appspot.com',
    iosBundleId: 'cmenu.app.za',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtwwXhgPk_WpaS8Pu1joPovte0OrBCP6g',
    appId: '1:279438736618:ios:2e2b055175492b9453eb93',
    messagingSenderId: '279438736618',
    projectId: 'cmenu-8af16',
    storageBucket: 'cmenu-8af16.appspot.com',
    iosBundleId: 'com.example.cmenu.RunnerTests',
  );
}
